services:
  jenkins_v1:
    build:
      context: .
      dockerfile: cicd/jenkins/Dockerfile
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
      - app_dist:/var/jenkins_home/dist
    environment:
      #Djenkins.install.runSetupWizard=false dùng để bỏ qua bước setup các plugin
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Duser.timezone=Asia/Ho_Chi_Minh
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yaml
    env_file:
      - .env
    networks:
      - ci_network

  nginx_v1:
    build:
      context: .
      dockerfile: cicd/nginx/Dockerfile
    ports:
      - '80:80'
    volumes:
      - app_dist:/usr/share/nginx/html
      - ./cicd/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - jenkins_v1
    networks:
      - ci_network

volumes:
  jenkins_home:
  app_dist:

networks:
  ci_network:
    driver: bridge
